### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ahmedtaa** [joskalenda/awesome-book-ES6#2]
**You did a good job there, the code is very organized** 
- we suggest a small arrangement for the code and we suggest that you move this line to index.js before creating a Book object.

https://github.com/joskalenda/awesome-book-ES6/blob/60c7abef891891cf5f15d1c087495c69b809f50d/src/module/script.js#L39

- Also we suggest that you remove the border that shows up when the book array is empty

**Comment by joskalenda** [comment]
Hello Ahmed.
Thanks for mentioning these issues, I will take them into consideration.
pleased. 🤝
